export const CLOCKFACTS = [
  "The world's most accurate clock, as of 2022, is the NIST-F2 cesium fountain atomic clock, accurate to within one second in 300 million years.",
  "The concept of the second as a unit of time was first introduced by the ancient Egyptians, who divided the day into 24 hours, each hour into 60 minutes, and each minute into 60 seconds.",
  "Sundials, one of the earliest timekeeping devices, have been used for thousands of years. They work by casting a shadow that moves as the sun travels across the sky.",
  "Water clocks, known as clepsydrae, were used in ancient civilizations like Egypt and China, measuring time by the flow of water from one container to another.",
  "The word 'clock' comes from the Middle English word 'clokke,' meaning 'bell,' as early mechanical clocks often had bells to signal the time.",
  "The first mechanical clocks were developed in medieval Europe, primarily found in churches and monasteries.",
  "The pendulum clock, invented by Christiaan Huygens in 1656, significantly improved timekeeping accuracy and was used for centuries.",
  "The first alarm clock was created by Plato in the 4th century BCE, working by releasing water through a hole, making a whistle sound at a certain level.",
  "In 1967, the International System of Units (SI) redefined the second based on the vibrations of a cesium atom, improving time measurement accuracy.",
  "A digital clock displays time using numerals, while an analog clock uses hands to indicate the hours, minutes, and sometimes seconds.",
  "The 'Doomsday Clock' is a symbolic representation indicating how close the world is to a global catastrophe, maintained by the Bulletin of the Atomic Scientists.",
  "Daylight Saving Time (DST) was first proposed by Benjamin Franklin in 1784 to conserve energy by maximizing daylight during the longer days of summer.",
  "The word 'horology' refers to the study and measurement of time and the art and science of designing and making timekeeping instruments.",
  "The 'tick-tock' sound made by a clock's pendulum inspired Edgar Allan Poe's poem 'The Tell-Tale Heart.'",
  "The world's most famous clock tower, Big Ben, is part of the Palace of Westminster in London. 'Big Ben' originally referred to the Great Bell inside the tower.",
  "The hourglass, a timekeeping device using sand to measure time, has been used for centuries and is still used today, especially in board games.",
  "The Swiss city of Geneva is famous for its watchmaking industry and home to prestigious watchmakers like Rolex and Patek Philippe.",
  "A 'sundial bridge' is a type of bridge that also serves as a sundial, with its shadow indicating the time of day.",
  "The first mechanical wristwatch was created by Patek Philippe in 1868, made for a Hungarian countess.",
  "The longest-running scientific experiment is the Pitch Drop Experiment at the University of Queensland, demonstrating the flow of a tar-like substance over time. The most recent drop occurred in 2014, marking the ninth drop since the experiment began in 1927.",
];